-- Neon recreation of tim.agent_runs (source: M900 postgres-tim, db gadgetlab)
-- Extracted 2026-07-04. Apply to a fresh Neon Postgres, then repoint the two
-- n8n Postgres credentials at Neon. Only 2 test rows existed in the source;
-- nothing worth migrating, so this is a clean create.

CREATE SCHEMA IF NOT EXISTS tim;

CREATE TABLE IF NOT EXISTS tim.agent_runs (
    id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id               text NOT NULL UNIQUE,
    issue_number         integer,
    issue_title          text,
    issue_body           text,
    repo                 text,
    sender               text,
    dreamer_output       jsonb,
    realist_output       jsonb,
    critic_output        jsonb,
    final_recommendation text,
    final_priority       text,
    created_at           timestamptz DEFAULT now(),
    updated_at           timestamptz,
    CONSTRAINT agent_runs_final_priority_check
        CHECK (final_priority = ANY (ARRAY['P0','P1','P2','ITERATE','DEFER']))
);

CREATE INDEX IF NOT EXISTS idx_agent_runs_created  ON tim.agent_runs USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_runs_priority ON tim.agent_runs USING btree (final_priority);
CREATE INDEX IF NOT EXISTS idx_agent_runs_repo     ON tim.agent_runs USING btree (repo);
